app:
  default_year: 2026
  server:
    host: "0.0.0.0"
    port: 3032

scraping:
  cache:
    html_directory: "html"
    csv_directory: "csv"
  tor:
    socks_port: 9050
    control_port: 9051

season_ids:
  2014: 4
  2015: 5
  2016: 6
  2017: 7
  2018: 8
  2019: 14
  2020: 15
  2021: 16
  2022: 17
  2023: 18
  2024: 19
  2025: 20
  2026: 21

urls:
  calendar_base: "https://play.usaultimate.org/events/tournament/"
  college_schedule: "https://usaultimate.org/college/schedule/"
  club_schedule: "https://usaultimate.org/club/schedule/"

scheduler:
  calendar_interval_hours: 8
  ongoing_interval_minutes: 10
  ongoing_team_refresh_interval_hours: 12
  upcoming_interval_hours: 12
  recently_ended_interval_hours: 8
  videos_interval_hours: 24
  wfdf_ongoing_interval_minutes: 10
  wfdf_roster_refresh_interval_hours: 12
  wfdf_upcoming_interval_hours: 12

divisions:
  "College - Men": "Men/CollegeMen/"
  "College - Men's": "Men/CollegeMen/"
  "D-I Men": "Men/CollegeMen/"
  "D-III Men": "Men/CollegeMen/"
  "Men's Lower Division": "Men/CollegeMen/"
  "Men's Developmental Division": "Men/CollegeMen/"
  "Dev Men": "Men/CollegeMen/"
  "Dev Women": "Women/CollegeWomen/"
  "College Women": "Women/CollegeWomen/"
  "College - Women": "Women/CollegeWomen/"
  "College - Women's": "Women/CollegeWomen/"
  "College Women's  (Division I)": "Women/CollegeWomen/"
  "College - Mixed": "mixed/College-Mixed/"
  "D-I Women": "Women/CollegeWomen/"
  "D-III Women": "Women/CollegeWomen/"
  "Womxn's Lower Division": "Women/CollegeWomen/"
  "Womxn's Upper Division": "Men/CollegeMen/"
  "Club - Men": "Men/Club-Men/"
  "College - Open": "Men/Club-Men"
  "Club - Men's": "Men/Club-Men/"
  "Club - Men Elite": "Men/Club-Men/elite/"
  "Club - Men Classic": "Men/Club-Men/classic"
  "College D-I Men": "Men/CollegeMen/college_d_i_men/"
  "College D-III Men": "Men/CollegeMen/college_d_iii_men/"
  "College - Men DIII (Division III)": "Men/CollegeMen/division_iii/"
  "Men's Upper Division": "Men/CollegeMen/men_s_upper_division/"
  "Mixed": "mixed/College-Mixed/"
  "Club - Women": "Women/Club-Women/"
  "Club - Women's": "Women/Club-Women/"
  "Club - Women  (Classic)": "Women/Club-Women/classic/"
  "Club - Women Elite": "Women/Club-Women/elite/"
  "Club Mixed": "Mixed/Club-mixed/"
  "Club - Mixed Elite": "mixed/Club-mixed/elite/"
  "Club - Mixed Classic": "mixed/Club-mixed/classic/"
  "Club - Mixed": "Mixed/Club-Mixed"
  "Club - Mixed's": "Mixed/Club-Mixed"
  "High School - Boys": "Boys/High-School-Boys/"
  "High School - Boys Varsity": "Boys/High-School-Boys/high_school_boys_varsity/"
  "High School - Boys 2 JV (High School - Boys JV)": "Boys/High-School-Boys/high_school_boys_jv/"
  "High School - Boys Elk Ridge Park": "Boys/High-School-Boys/boys_elk_ridge_park/"
  "High School - Boys Sky View": "Boys/High-School-Boys/boys_sky_view/"
  "High School - Boys  (HS Boys)": "Boys/High-School-Boys/hs_boys/"
  "High School - Boys B (HS Boys B)": "Boys/High-School-Boys/hs_boys_b/"
  "HS Open - Div I": "Boys/High-School-Boys/"
  "High School - Girls Green Canyon High School": "Girls/High-School-Girls/"
  "High School - Girls": "Girls/High-School-Girls/"
  "High School - Mixed": "Mixed/High-School-Mixed/"
  "Masters - Men": "Men/Masters-Men/"
  "Masters - Mixed": "Mixed/Masters-Mixed/"
  "Masters - Women": "Women/Masters-Women/"
  "Grand Masters - Men": "Men/grand-masters-men/"
  "Grand Masters - Women": "Women/grand-masters-women/"
  "Grand Masters - Mixed": "mixed/grand-masters-mixed/"
  "Great Grand Masters - Men": "Men/great-grand-masters-men/"
  "Great Grand Masters - Women": "Women/great-grand-masters-women/"
  "Men's Division": "Men/CollegeMen/"
  "Men A Division": "Men/Club-Men/a_division/"
  "Men B Division": "Men/Club-Men/b_division"
  "U20 - Boys": "Boys/High-School-Boys/"
  "U20 - Girls": "Girls/High-School-Girls/"
  "Youth Club U-20 - Boys": "Boys/youth-club-u-20-boys/"
  "U20 Boys Youth Club": "Boys/youth-club-u-20-boys/"
  "Youth Club U19 - Boys": "Boys/youth-club-u-20-boys/"
  "Youth Club U-20 - Girls": "Girls/youth-club-u-20-girls/"
  "U20 Girls Youth Club": "Girls/youth-club-u-20-girls/"
  "Youth Club U19 - Girls": "Girls/youth-club-u-20-girls/"
  "Youth Club U-20 - Mixed": "Mixed/youth-club-u-20-mixed/"
  "U20 Mixed Youth Club": "Mixed/youth-club-u-20-mixed/"
  "Youth Club U19 - Mixed": "Mixed/youth-club-u-20-mixed/"
  "Youth Club U-17 - Boys": "Boys/youth-club-u-17-boys/"
  "Youth Club U16 - Boys": "Boys/youth-club-u-17-boys/"
  "Youth Club U-17 - Girls": "Girls/youth-club-u-17-girls/"
  "Youth Club U16 - Girls": "Girls/youth-club-u-17-girls/"
  "Youth Club Girls - U20 & U17": "Girls/youth-club-u-20-girls/"
  "Middle School - Mixed": "mixed/Middle-School-Mixed/"
  "Middle School - Boys": "Boys/Middle-School-Boys/"
  "Beach - Men": "Men/Beach-Mens/"
  "Beach - Women": "Women/Beach-Womens/"
  "Beach - Mixed": "mixed/Beach-Mixed"
  "Beach Masters - Mixed": "mixed/Beach-Masters-Mixed/"
  "Beach Grand Masters - Men": "Men/Beach-Grand-Masters-Men/"
  "Beach Great Grand Masters - Men": "Men/beach-great-grand-masters-men/"
  "Tally Classic - Women": "Women/CollegeWomen/"
  "Tally Classic - Men": "Men/CollegeMen/"
